apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-stream
  namespace: iot-simulators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-stream
  template:
    metadata:
      labels:
        app: video-stream
    spec:
      containers:
      - name: video-stream-container
        image: mcs2503/video-stream:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RTMP_SERVER
          value: "rtmp://nginx-service.streaming-slice.svc.cluster.local:1935/live/$(POD_NAME)"
        envFrom:
        - configMapRef:
            name: ffmpeg-config

